language: node_js

node_js:
  - '6'

notifications:
  email:
    on_success: change
    on_failure: always

# Use container-based Travis infrastructure.
sudo: required
dist: trusty

addons:
  chrome: stable
  firefox: "latest"  

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - npm run lint
  - ./scripts/travis/test.sh

jobs:
  include:
    - script: npm run lint
    - script: npm run test:coveralls
    - script: npm run test:browser
    - stage: Build
      script:
        - npm run build
        - npm run test:package
